import { Card } from "@/components/ui/Card";
import { RESELLER_SUMMARY } from "@/lib/mock-data/resellers";

/** "Total Active Resellers / Total GMV / Total Commission Paid Out" stat row shown above the
 *  Reseller Management filters bar — matches the Figma "re-seller" design's three summary cards
 *  (plain white tiles, no icons, unlike `InventoryStatsCards`'s icon-badge treatment). */
export function ResellerStatsCards() {
  return (
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
      <Card className="flex min-w-0 flex-col gap-2.5 p-[19px]">
        <p className="min-w-0 break-words text-[13px] font-bold text-gray-500">Total Active Resellers</p>
        <p className="break-words text-[28px] font-extrabold tracking-[-1.12px] text-ink">
          {RESELLER_SUMMARY.totalActiveResellers}
        </p>
        <p className="break-words text-[13px] font-medium text-gray-500">{RESELLER_SUMMARY.totalActiveResellersNote}</p>
      </Card>

      <Card className="flex min-w-0 flex-col gap-2.5 p-[19px]">
        <p className="min-w-0 break-words text-[13px] font-bold text-gray-500">Total GMV Generated by Resellers (₹)</p>
        <p className="break-words text-[28px] font-extrabold tracking-[-1.12px] text-ink">{RESELLER_SUMMARY.totalGmv}</p>
        <p className="break-words text-[13px] font-medium text-gray-500">{RESELLER_SUMMARY.totalGmvNote}</p>
      </Card>

      <Card className="flex min-w-0 flex-col gap-2.5 p-[19px]">
        <p className="min-w-0 break-words text-[13px] font-bold text-gray-500">Total Commission Paid Out (₹)</p>
        <p className="break-words text-[28px] font-extrabold tracking-[-1.12px] text-ink">
          {RESELLER_SUMMARY.totalCommissionPaidOut}
        </p>
        <p className="break-words text-[13px] font-medium text-gray-500">{RESELLER_SUMMARY.totalCommissionNote}</p>
      </Card>
    </div>
  );
}
